### ISSUE TITLE
Could you please make the same for win32 ?

### ISSUE THREAD

**Issue by 10mitri** [sclem/node-sqlite3-prebuilt#1]
Thank you for this. Could you please make the same for win32 ?

**Comment by sclem** [comment]
Done

**Comment by 10mitri** [comment]
Thanks a lot.
But I still have a problem.
It says :

module.js:670
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Le module spécifié est introuvable. [This specified module could not be found]
\\?\D:\MC\PERSO\dev\projet\node.js\node_modules\sqlite3\lib\binding\node-v59-win
32-ia32\node_sqlite3.node
    at Object.Module._extensions..node (module.js:670:18)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\MC\PERSO\dev\projet\node.js\node_modules\sqlite3\l
ib\sqlite3.js:4:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)

[Win 7 32, portable Node 9.2.0]

**Comment by sclem** [comment]
The folder path is incorrect. You want `node_modules\sqlite3\lib\binding\node-webkit-v0.26.6-win32-ia32\node_sqlite3.node`, not `node-v59`

**Comment by 10mitri** [comment]
I have been away for a while.
Still doesn't work. With the same message.
It really seems to wait the file in node-v59. Whenever I put it in the node-v59 or webkit-v0.26.6, the message is the same.

**Comment by 10mitri** [comment]
more precisely 👍 
module.js:670
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Le module spécifié est introuvable.
\\?\D:\MC\PERSO\dev\projet\node.js\node_modules\sqlite3\lib\binding\node-v59-win
32-ia32\node_sqlite3.node
    at Object.Module._extensions..node (module.js:670:18)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\MC\PERSO\dev\projet\node.js\node_modules\sqlite3\l
ib\sqlite3.js:4:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
